name: MyDotNetCore-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish --configuration Release --output dotnetcorewebapp
      
    - name: Upload result publish
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: dotnetcorewebapp
  
  deploy:
    
    needs: build
    name: Deploy App
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Host Name
        run: hostname
        
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: myapplication/artifact

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: myapplication/artifact
      
      - uses: azure/login@v1
        name: Azure Login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/webapps-deploy@v1
        with:
          app-name: 'githubactionsleandro'
          package: myapplication/artifact
      
      - name: Azure Logout
        run: az logout
